# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e10204eca0d5aa413994dc9eefecd14a31acf1072f45e6ffce09dadf4cb5e86635b53ef278190857e9a28abbb82cc17d8d8cd1ee320f7de139bd26b968783e04

test:
  secret_key_base: d07990de0d4f4aef3aba71cf382bff5a78b563d8bcf7ba9df865ac75da17658f1242085c2385d8cca6f671dce9fd003cf7de56b02d0e382744648b42505c4003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
